WaitingForItem = false

RollInfo = {
    isRolling = false,
    user = nil,
    item = nil,
    bets = {},
    bet = 0
}

Wearables = {
    'Plate',
    'Mail',
    'Leather',
    'Cloth'
}

ClassWearables = {
    DeathKnight = 'Plate',
    Druid = 'Leather',
    Hunter = 'Mail',
    Mage = 'Cloth',
    Paladin = 'Plate',
    Priest = 'Cloth',
    Rogue = 'Leather',
    Shaman = 'Mail',
    Warlock = 'Cloth',
    Warrior = 'Plate'
}

SupportedEquipables = {
    'One-Handed Maces',
    'Two-Handed Maces',
    'One-Handed Swords',
    'Two-Handed Swords',
    'One-Handed Axes',
    'Two-Handed Axes',
    'Polearms',
    'Daggers',
    'Shields',
    'Fist',
    'Bows',
    'Guns',
    'Crossbows',
    'Thrown',
    'Staves',
    'Wands',
    'Relic',
}

ClassEquipables = {
    DeathKnight = {
        'One-Handed Axes',
        'Two-Handed Axes',
        'One-Handed Swords',
        'Two-Handed Swords',
        'One-Handed Maces',
        'Two-Handed Maces',
        'Polearms',
        'Relic',
    },
    Druid = {
        'One-Handed Maces',
        'Two-Handed Maces',
        'Polearms',
        'Staves',
        'Daggers',
        'Fist',
        'Relic',
    },
    Hunter = {
        'One-Handed Axes',
        'Two-Handed Axes',
        'One-Handed Swords',
        'Two-Handed Swords',
        'Polearms',
        'Staves',
        'Daggers',
        'Fist',
        'Bows',
        'Crossbows',
        'Guns',
    },
    Mage = {
        'One-Handed Swords',
        'Two-Handed Swords',
        'Staves',
        'Daggers',
        'Wands',
    },
    Paladin = {
        'One-Handed Axes',
        'Two-Handed Axes',
        'One-Handed Swords',
        'Two-Handed Swords',
        'One-Handed Maces',
        'Two-Handed Maces',
        'Polearms',
        'Relic',
    },
    Priest = {
        'One-Handed Maces',
        'Staves',
        'Daggers',
        'Wands',
    },
    Rogue = {
        'One-Handed Axes',
        'One-Handed Swords',
        'One-Handed Maces',
        'Daggers',
        'Fist',
        'Bows',
        'Crossbows',
        'Guns',
        'Thrown',
    },
    Shaman = {
        'One-Handed Axes',
        'Two-Handed Axes',
        'One-Handed Maces',
        'Two-Handed Maces',
        'Polearms',
        'Staves',
        'Daggers',
        'Fist',
        'Relic',
    },
    Warlock = {
        'One-Handed Swords',
        'Two-Handed Swords',
        'Staves',
        'Daggers',
        'Wands',
    },
    Warrior = {
        'One-Handed Maces',
        'Two-Handed Maces',
        'One-Handed Swords',
        'Two-Handed Swords',
        'One-Handed Axes',
        'Two-Handed Axes',
        'Polearms',
        'Staves',
        'Daggers',
        'Fist',
        'Bows',
        'Crossbows',
        'Guns',
        'Thrown',
    },
}
